# Generated by Django 4.2 on 2023-04-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                ("periodo_semestral", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_estudiantil", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grades_app.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grades_app.estudiante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SCC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("correo_electronico", models.EmailField(max_length=254)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PROFESOR", "Profesor"),
                            ("ADMINISTRADOR", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoDeAprendizaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "scc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grades_app.scc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grades_app.actividad",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grades_app.inscripcion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadorDeLogro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "resultado_de_aprendizaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grades_app.resultadodeaprendizaje",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="resultados_de_aprendizaje",
            field=models.ManyToManyField(to="grades_app.resultadodeaprendizaje"),
        ),
        migrations.AddField(
            model_name="actividad",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="grades_app.curso"
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="resultado_de_aprendizaje",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="grades_app.resultadodeaprendizaje",
            ),
        ),
    ]
