# Generated by Django 4.2 on 2023-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades_app", "0002_alter_scc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scc",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
